name: 'Build NULIX OS with custom apps'
description: 'Build and Deploy NULIX OS with custom apps'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Fetch base NULIX OS
      uses: 'docker://nulix/builder:os'
      id: fetch-base-os
      run: entrypoint.sh fetch-base-os
      shell: bash
    - name: Inject custom apps
      uses: 'docker://nulix/builder:os'
      id: inject-apps
      run: entrypoint.sh inject-apps
      shell: bash
