name: 'Build NULIX OS with custom apps'
description: 'Build and Deploy NULIX OS with custom apps'
author: 'NULIX'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  step_name:
    description: 'Name of the step being executed.'
    required: true
  input_data:
    description: 'Data to process in the step.'
    required: false
    default: 'default data'
outputs:
  step_output:
    description: 'Output from the step.'
runs:
  using: 'docker'
  image: 'docker://nulix/builder:os'
  entrypoint: 'entrypoint.sh'
