name: 'Build NULIX OS with custom apps'
description: 'Build and Deploy NULIX OS with custom apps'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - name: Fetch base NULIX OS
      uses: 'docker://nulix/builder:os'
      shell: bash
      run: |
        source /nulix-os-venv/bin/activate
        west init -m https://github.com/nulix/nulix-os.git nulix-os
        cd nulix-os
        west update
        source tools/setup-environment
        cd build/deploy/$MACHINE
        wget https://files.0xff.com.hr/$MACHINE/$OSTREE_ROOTFS-$NULIX_OS_VER.tar.gz
        wget https://files.0xff.com.hr/$MACHINE/$OSTREE_REPO.tar.gz
        tar xzf $OSTREE_REPO.tar.gz
        mv -v $OSTREE_REPO ../../../rootfs
        mv -v $OSTREE_ROOTFS-*.tar.gz ../../../rootfs
        rm $OSTREE_REPO.tar.gz
        cd ../../..
        rm -f rootfs/$OSTREE_REPO.tar.gz
