name: 'Build NULIX OS with custom apps'
description: 'Build and Deploy NULIX OS with custom apps'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - id: entrypoint
      name: Run entrypoint.sh
      run: entrypoint.sh fetch-base-os
      shell: bash
    - name: Inject custom apps
      uses: 'docker://nulix/builder:os'
      with:
        entrypoint: echo
        args: 1234567890
