name: "Build and deploy NULIX OS with custom apps"
description: "Build NULIX OS with custom apps, and deploy OTA updates"
author: "NULIX"
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  step_name:
    description: "Name of the step being executed"
    required: true
  machine:
    description: "Machine name"
    required: false
    default: "rpi3"
  distro:
    description: "Distro name"
    required: false
    default: "alpine-docker"
  apps_repo:
    description: "Repository with custom apps"
    required: false
    default: "https://github.com/nulix/apps.git"
  apps_git_ref:
    description: "Git reference for custom apps"
    required: false
    default: "main"
  compose_file:
    description: "Docker compose YAML file name"
    required: false
    default: "docker-compose.yml"
  ssh_public_key:
    description: "Public SSH key"
    required: false
  ssl_cert:
    required: false
    description: "Custom SSL certificate"
  upd8_api_url:
    required: false
    description: "Custom UPD8 API URL"
  git_token:
    required: false
  upd8_keys:
    required: true
  machine_reg_token:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GIT_TOKEN: ${{ inputs.git_token }}
    UPD8_KEYS: ${{ inputs.upd8_keys }}
    MACHINE_REG_TOKEN: ${{ inputs.machine_reg_token }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    SSH_PUBLIC_KEY: ${{ inputs.ssh_public_key }}
    SSL_CERT: ${{ inputs.ssl_cert }}
    UPD8_API_URL: ${{ inputs.upd8_api_url }}
  args:
    - ${{ inputs.step_name }}
    - ${{ inputs.machine }}
    - ${{ inputs.distro }}
    - ${{ inputs.apps_repo }}
    - ${{ inputs.apps_git_ref }}
    - ${{ inputs.compose_file }}
