name: 'Build NULIX OS with custom apps'
description: 'Build and Deploy NULIX OS with custom apps'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - name: Fetch base NULIX OS
      uses: 'docker://nulix/builder:os'
      with:
        entrypoint: echo
        args: 1234567890
    - name: Fetch base NULIX OS
      uses: 'docker://nulix/builder:os'
      with:
        entrypoint: echo
        args: 0987654321
