on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy NULIX OS with apps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Deploy NULIX OS with apps
        id: build-and-deploy
        uses: ./ # Uses an action in the root directory
        # uses: nulix/os-with-apps-action@v0.0.1-alpha
