on: [push]

env:
  MACHINE: rpi3
  NULIX_OS_VER: 1.3.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy NULIX OS with apps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch base NULIX OS
        uses: ./ # Uses an action in the root directory
        # uses: nulix/os-with-apps-action@v0.0.1-alpha
        with:
          step_name: fetch-base-os
          machine: ${{ env.MACHINE }}
      - name: Inject custom apps
        uses: ./ # Uses an action in the root directory
        # uses: nulix/os-with-apps-action@v0.0.1-alpha
        with:
          step_name: inject-apps
          machine: ${{ env.MACHINE }}
      - name: Build OS image
        uses: ./ # Uses an action in the root directory
        # uses: nulix/os-with-apps-action@v0.0.1-alpha
        with:
          step_name: build-os-image
          machine: ${{ env.MACHINE }}
      - name: Upload OS image
        uses: actions/upload-artifact@v4
        with:
          name: nulix-os-${{ env.MACHINE }}-v${{ env.NULIX_OS_VER }}
          path: nulix-os/build/deploy/${{ env.MACHINE }}/nulix-os-${{ env.NULIX_OS_VER }}.img.bz2
          retention-days: 7  # Keep the artifact for 7 days
