name: Update Custom Apps Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      machine:
        description: 'Override the default MACHINE value'
        required: false
        type: string

env:
  MACHINE: ${{ github.event.inputs.machine || 'rpi3' }}

jobs:
  build-os:
    runs-on: ubuntu-latest
    name: Update custom apps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            action.yml
            docker-compose.yml
      - name: Update custom apps
        uses: ./
        with:
          step_name: update-apps
          machine: ${{ env.MACHINE }}
          api_key_secret: ${{ secrets.API_KEY }}
          machine_reg_token_secret: ${{ secrets.MACHINE_REG_TOKEN }}
